In [2]:
import pandas as pd
import numpy as np

# Data Cleaning

In [9]:
#import csv file
data=pd.read_csv('C:/Users/Anne_2/Documents/Ironhack/Fifa_Moneyball-Case-Study/fifa21_male2.csv', dtype={78: 'str'})

In [5]:
#view data file
pd.set_option('max_columns', None)
data.head()

,ID,Name,Age,OVA,Nationality,Club,BOV,BP,Position,Player Photo,Club Logo,Flag Photo,POT,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,Gender
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0,Male
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1,Male
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0,Male
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0,Male
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3,Male

In [8]:
print(data.columns.tolist())

['ID', 'Name', 'Age', 'OVA', 'Nationality', 'Club', 'BOV', 'BP', 'Position', 'Player Photo', 'Club Logo', 'Flag Photo', 'POT', 'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'Gender']

In [6]:
#keeping only columns relevant for analysis and a few descriptives
data = data.filter(['ID', 'Name', 'Age', 'OVA', 'Nationality', 'Club', 'BP', 'Height', 'Weight', 'foot', 'Value', 'Wage', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Gender'], axis=1)

In [10]:
#standardizing column names
data.columns=[i.lower().replace(' ','_') for i in data.columns]

In [11]:
#Checking number of entries and for duplicates on ID
print(data.shape)
print('Duplicate ids:', data['id'].duplicated().sum())

(17125, 53)
Duplicate ids: 0

In [12]:
#checking for null values
data.isna().sum()

id                    0
name                  0
age                   0
ova                   0
nationality           0
club                 23
bp                    0
height                0
weight                0
foot                  0
value                 0
wage                  0
crossing              0
finishing             0
heading_accuracy      0
short_passing         0
volleys              58
dribbling             0
curve                58
fk_accuracy           0
long_passing          0
ball_control          0
acceleration          0
sprint_speed          0
agility              58
reactions             0
balance              58
shot_power            0
jumping              58
stamina               0
strength              0
long_shots            0
aggression            0
interceptions         7
positioning           7
vision               58
penalties             0
composure           423
marking               0
standing_tackle       0
sliding_tackle       58
gk_diving             0
gk_handling           0
gk_kicking            0
gk_positioning        0
gk_reflexes           0
pac                   0
sho                   0
pas                   0
dri                   0
def                   0
phy                   0
gender                0
dtype: int64

In [13]:
data['position'] = str
data['position'] = np.where(data['bp'] == 'LS', 'forward', data['bp'])

In [14]:
#Especially high number of missing values in 'composure'.
#Building categories of player positions and then check if null values concerning only certain positions
#if not, deleting all data rows with null values
data['bp'].value_counts()

CB     3252
ST     2660
CAM    2246
GK     1576
RM     1404
CDM    1246
CM      990
LB      921
RB      894
LM      805
RW      329
LWB     252
RWB     252
LW      209
CF       89
Name: bp, dtype: int64

In [15]:
#categories: forward, midfielder, defender, keeper
#new variable position, derived from column bp (best position)
def recode_position(x):
    if (x == 'ST' or x == 'CF'):
        return 'forward'
    elif (x == 'CB' or x == 'LB' or x =='RB' or x == 'RWB' or x == 'LWB'):
        return 'defender'
    elif x == 'GK':
        return 'keeper'
    else:
        return 'midfielder'

data['position'] = data['bp'].apply(recode_position)

In [16]:
#check recoding
pd.crosstab(data['bp'], data['position'])

position  defender  forward  keeper  midfielder
bp
CAM              0        0       0        2246
CB            3252        0       0           0
CDM              0        0       0        1246
CF               0       89       0           0
CM               0        0       0         990
GK               0        0    1576           0
LB             921        0       0           0
LM               0        0       0         805
LW               0        0       0         209
LWB            252        0       0           0
RB             894        0       0           0
RM               0        0       0        1404
RW               0        0       0         329
RWB            252        0       0           0
ST               0     2660       0           0

In [17]:
#check missing values within groups
data.groupby(['position'])[['id','composure']].count()

              id  composure
position
defender    5571       5444
forward     2749       2660
keeper      1576       1542
midfielder  7229       7056

In [18]:
#missing values seem to be randomly spread across groups - deleting all rows with missing values
data=data.dropna(axis=0)
data.shape

(16687, 54)

In [19]:
#checking datatypes of columns
data.dtypes

id                    int64
name                 object
age                   int64
ova                   int64
nationality          object
club                 object
bp                   object
height               object
weight               object
foot                 object
value                object
wage                 object
crossing              int64
finishing             int64
heading_accuracy      int64
short_passing         int64
volleys             float64
dribbling             int64
curve               float64
fk_accuracy           int64
long_passing          int64
ball_control          int64
acceleration          int64
sprint_speed          int64
agility             float64
reactions             int64
balance             float64
shot_power            int64
jumping             float64
stamina               int64
strength              int64
long_shots            int64
aggression            int64
interceptions       float64
positioning         float64
vision              float64
penalties             int64
composure           float64
marking               int64
standing_tackle       int64
sliding_tackle      float64
gk_diving             int64
gk_handling           int64
gk_kicking            int64
gk_positioning        int64
gk_reflexes           int64
pac                   int64
sho                   int64
pas                   int64
dri                   int64
def                   int64
phy                   int64
gender               object
position             object
dtype: object

In [20]:
#checking on column 'value', it should be numerical for analysis
data['value'].head(5)

1     €600K
4     €5.5M
6     €2.8M
12    €5.5M
26    €2.2M
Name: value, dtype: object

In [21]:
#delete '€' sign and split column into number and unit
data['value']=[i.replace('€','') for i in data['value']]
data['unit'] = data['value'].str[-1:]
data['number']=[i.replace('K','') for i in data['value']]
data['number']=[i.replace('M','') for i in data['number']]
data['number']=data['number'].astype(float)

In [22]:
data['number'].head()

1     600.0
4       5.5
6       2.8
12      5.5
26      2.2
Name: number, dtype: float64

In [23]:
data['unit'].value_counts()

K    9161
M    7207
0     319
Name: unit, dtype: int64

In [24]:
#multiply number column by unit
data['unit']=[i.replace('0', '1') for i in data['unit']]
data['unit']=[i.replace('K', '1000') for i in data['unit']]
data['unit']=[i.replace('M', '1000000') for i in data['unit']]
data['unit']=data['unit'].astype(int)

data['market_value'] = (data['unit']*data['number']).astype(int)

In [25]:
data['market_value'].head()

1      600000
4     5500000
6     2800000
12    5500000
26    2200000
Name: market_value, dtype: int32

In [26]:
data = data.drop(['unit', 'number'], axis=1)

In [4]:
#dividing market value again by 1.000.000 to make number more readable
data['market_value']=data['market_value']/1000000
data['market_value'].head()

0    0.6
1    5.5
2    2.8
3    5.5
4    2.2
Name: market_value, dtype: float64

In [5]:
#checking values of numeric variables, especially all skills should be between 0 and 100 (score)
data.describe()

,id,age,ova,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,...,gk_kicking,gk_positioning,gk_reflexes,pac,sho,pas,dri,def,phy,market_value
count,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,...,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000,16687.000000
mean,221917.732187,25.152694,66.913945,51.520825,47.870738,53.475999,60.429196,44.862468,57.804578,49.446036,...,15.331575,15.490621,15.715947,68.172949,54.863786,58.834662,64.173968,50.251154,64.905316,2.610607
std,31885.463182,4.854647,6.824825,17.854763,19.382450,16.904378,13.923891,17.669834,18.050802,18.139971,...,15.797503,16.380050,17.135799,11.087874,13.859216,10.140233,9.814026,16.806651,9.644012,5.428192
min,16.000000,16.000000,45.000000,6.000000,3.000000,5.000000,7.000000,4.000000,5.000000,4.000000,...,1.000000,1.000000,1.000000,25.000000,16.000000,25.000000,28.000000,12.000000,27.000000,0.000000
25%,205437.000000,21.000000,62.000000,40.000000,33.000000,46.000000,56.000000,32.000000,53.000000,37.000000,...,8.000000,8.000000,8.000000,62.000000,45.000000,52.000000,59.000000,35.000000,59.000000,0.375000
50%,229768.000000,25.000000,67.000000,56.000000,52.000000,57.000000,63.000000,46.000000,63.000000,51.000000,...,11.000000,11.000000,11.000000,69.000000,58.000000,59.000000,65.000000,53.000000,66.000000,0.800000
75%,244200.500000,29.000000,72.000000,65.000000,63.000000,65.000000,69.000000,58.000000,70.000000,64.000000,...,14.000000,14.000000,14.000000,75.000000,65.000000,66.000000,71.000000,64.000000,72.000000,2.500000
max,259105.000000,53.000000,93.000000,94.000000,95.000000,93.000000,94.000000,90.000000,96.000000,94.000000,...,93.000000,91.000000,90.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000,105.500000

####  Market value seems to have some extreme outliers as well as entries with a market value of '0'. It is not clear, if a market value of '0' is a missing value or an actual 'not worth anything value' or players, that are not available to the market anymore for whatever reasons... For analysis of skills and their impact on market value, reducing the dataset to players that: A) have a market value at all, B) don't belong to extreme outliers, since these extreme market values most likely are produced by factors other than basic playing skills

In [7]:
# market value before dropping
data['market_value'].describe()

count    16687.000000
mean         2.610607
std          5.428192
min          0.000000
25%          0.375000
50%          0.800000
75%          2.500000
max        105.500000
Name: market_value, dtype: float64

In [9]:
#skipping data with market value = 0
data=data[data['market_value']>0]
data['market_value'].describe()

count    16368.000000
mean         2.661486
std          5.468467
min          0.003000
25%          0.400000
50%          0.850000
75%          2.500000
max        105.500000
Name: market_value, dtype: float64

In [12]:
#removing outliers of market_value
iqr = np.percentile(data['market_value'], 75) - np.percentile(data['market_value'],25)
lower_limit= np.percentile(data['market_value'],25)-1.5*iqr
upper_limit= np.percentile(data['market_value'], 75)+1.5*iqr
data=data[(data['market_value']>lower_limit)&(data['market_value']<upper_limit)]
data.reset_index(drop=True, inplace=True)
data['market_value'].describe()

count    14309.000000
mean         1.183116
std          1.253751
min          0.003000
25%          0.350000
50%          0.700000
75%          1.400000
max          5.500000
Name: market_value, dtype: float64

In [13]:
#saving cleaned data set
data.to_csv('C:/Users/Anne_2/Documents/Ironhack/Fifa_Moneyball-Case-Study/fifa21_cleaned.csv', index=False)